# TEMPLATE
#  0XEZPioQQwZfuiTpVAGNlp - anime chill
addToPlaylist:
  f7: 0XEZPioQQwZfuiTpVAGNlp

removeFromPlaylist:
  f8: 0XEZPioQQwZfuiTpVAGNlp


addToLiked: f3
removeFromLiked: f2

updateShortcuts: f9
# toggleLoop: key
# toggleShuffle: key
pause: pause
close: f10