# TEMPLATE 
# Modify only "key" and "playlist_id"
# Don't use tabs, only 2 whitespaces

addToPlaylist:
  key: playlist_id

  # if you want a shortcut with multiple keys, use this syntax
  <key>+<key>: playlist_id

removeFromPlaylist:
  key: playlist_id
  key: playlist2_id


addToLiked: key
removeFromLiked: key

updateShortcuts: key
toggleLoop: key
toggleShuffle: key
pause: key
close: key


# SAVE THIS FILE TO config.yaml