# TEMPLATE (change only "key" and "playlist_id")

addToPlaylist:
  key: playlist_id

removeFromPlaylist:
  key: playlist_id


addToLiked: key
removeFromLiked: key

updateShortcuts: key
toggleLoop: key
toggleShuffle: key
pause: key
close: key 
